export const VALIDATION_VERSION = 1;
export const LONG_SESSION_SECONDS = 90 * 60;
export const REVIEW_SESSION_SECONDS = 120 * 60;
export const HIGH_RISK_SESSION_SECONDS = 180 * 60;
export const READING_CONTINUOUS_LIMIT_SECONDS = 5 * 60 * 60;
export const CLOCK_MISMATCH_TOLERANCE_SECONDS = 5 * 60;
