import { ENEMY_CATALOG } from '../../rpg/enemyCatalog.js';
import BattleArena from './BattleArena.jsx';
import EnemyCard from './EnemyCard.jsx';
import VictoryResult from './VictoryResult.jsx';
import DefeatResult from './DefeatResult.jsx';
import { getChapter } from '../../rpg/chapterCatalog.js';
import { getBoss } from '../../rpg/bossCatalog.js';
import { isBossUnlocked, normalizeRpgProgress } from '../../rpg/rpgProgress.js';
import { MATERIAL_DEFS } from '../../rpg/rewardConfig.js';
export default function BattlePanel({ profile, progress, battle, onStartRequest, onAttack, onSkill, startingEnemyId, attacking, onBack, feedback }) { if (battle?.status === 'won') return <VictoryResult battle={battle}/>; if (battle?.status === 'lost') return <DefeatResult battle={battle} onBack={onBack}/>; if (battle?.status === 'active') return <BattleArena battle={battle} onAttack={onAttack} onSkill={onSkill} attacking={attacking} feedback={feedback}/>; const safe = normalizeRpgProgress(progress); const chapter = getChapter(safe.currentChapterId); const boss = getBoss(chapter.bossId); const unlocked = isBossUnlocked(safe, chapter); const remaining = Math.max(0, chapter.normalWinsRequired - safe.normalWins); return <section><p className="text-[10px] font-black tracking-widest text-rose-600">CHAPTER {chapter.number}</p><h2 className="text-xl font-black text-slate-800">{chapter.name}</h2><div className="mt-3 rounded-2xl bg-slate-100 p-4 text-sm font-bold text-slate-700">通常敵撃破 {safe.normalWins} / {chapter.normalWinsRequired}<div className="mt-2 h-2 overflow-hidden rounded bg-white"><div className="h-full bg-emerald-500" style={{ width: `${Math.min(100, safe.normalWins / chapter.normalWinsRequired * 100)}%` }}/></div><p className="mt-2 text-xs">{unlocked ? 'BOSS UNLOCKED' : `Boss解放まであと${remaining}勝`}</p></div><h3 className="mt-5 font-black text-slate-800">通常敵</h3><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{chapter.normalEnemyIds.map((id) => <EnemyCard key={id} enemy={ENEMY_CATALOG[id]} profile={profile} onStart={onStartRequest} starting={startingEnemyId === id}/>)}</div><article className="mt-5 rounded-2xl border-2 border-amber-300 bg-amber-50 p-5"><p className="text-[10px] font-black tracking-widest text-amber-700">BOSS {unlocked ? 'UNLOCKED' : 'LOCKED'}</p><h3 className="mt-1 font-black text-slate-800">{boss.name}</h3><p className="mt-2 text-xs font-bold text-slate-600">HP {boss.maxHp} ・ 攻撃力 {boss.attack} ・ Energy {boss.energyCost}</p><p className="mt-2 text-xs font-bold text-slate-600">初回報酬 GOLD +{boss.firstClearReward.gold} / {Object.entries(boss.firstClearReward.materials).map(([key, value]) => `${MATERIAL_DEFS[key]?.label || key} +${value}`).join(' / ')}</p><button type="button" disabled={!unlocked || (Number(profile.battleEnergy) || 0) < boss.energyCost || startingEnemyId === boss.id} onClick={() => onStartRequest?.({ ...boss, isBoss: true })} className="mt-4 w-full rounded-xl bg-amber-600 py-3 text-sm font-black text-white disabled:bg-slate-300">{unlocked ? 'BOSSに挑戦する' : `あと${remaining}勝で解放`}</button></article></section>; }
