import { EQUIPMENT_CATALOG, EQUIPMENT_SLOTS } from '../../rpg/equipmentCatalog.js';
import { normalizePlayerProfile } from '../../rpg/playerProfile.js';
import { groupOwnedEquipment, isEquipmentEquipped } from '../../rpg/shopUiLogic.js';
import { calculatePlayerAttack, calculatePlayerDefense, calculatePlayerMaxHp } from '../../rpg/battleCalculator.js';
import { getEquipmentDisplayStats } from '../../rpg/equipmentDisplay.js';

const SLOT_LABELS = { weapon: '武器', armor: '防具', accessory: 'アクセサリー' };
const ItemStats = ({ item }) => { const stats = getEquipmentDisplayStats(item); return <><div className="mt-3 grid grid-cols-2 gap-2 text-xs font-black"><div className="rounded-lg bg-blue-50 p-2 text-blue-700">攻撃力 +{stats.attack}</div><div className="rounded-lg bg-emerald-50 p-2 text-emerald-700">防御力 +{stats.defense}</div></div><p className="mt-2 text-xs font-bold text-slate-500">特殊能力：{stats.specialAbilityLabel}</p></>; };

export default function EquipmentPanel({ profile, onEquip, onUnequip, pendingAction }) {
  const safe = normalizePlayerProfile(profile || {});
  const grouped = groupOwnedEquipment(safe, EQUIPMENT_CATALOG);
  const total = { maxHp: calculatePlayerMaxHp(safe), attack: calculatePlayerAttack(safe), defense: calculatePlayerDefense(safe) };
  return <section className="space-y-6"><div><p className="text-[10px] font-black tracking-widest text-slate-400">EQUIPMENT</p><h2 className="text-xl font-black text-slate-800">現在の装備</h2></div><div className="rounded-2xl border border-violet-100 bg-violet-50 p-5"><p className="text-xs font-black text-violet-700">現在の戦闘ステータス</p><div className="mt-3 grid grid-cols-3 gap-2 text-center text-xs font-black"><div className="rounded-xl bg-white p-3 text-slate-700"><p className="text-slate-400">最大HP</p><p className="mt-1 text-lg">{total.maxHp}</p></div><div className="rounded-xl bg-white p-3 text-blue-700"><p className="text-slate-400">攻撃力</p><p className="mt-1 text-lg">{total.attack}</p></div><div className="rounded-xl bg-white p-3 text-emerald-700"><p className="text-slate-400">防御力</p><p className="mt-1 text-lg">{total.defense}</p></div></div></div><div className="grid gap-3 md:grid-cols-3">{EQUIPMENT_SLOTS.map((slot) => { const item = EQUIPMENT_CATALOG[safe.equipped[slot]]; return <div key={slot} className="min-w-0 rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><p className="text-[10px] font-black text-slate-400">{SLOT_LABELS[slot]}</p><p className="mt-2 break-words text-sm font-black text-slate-800">{item?.name || '未装備'}</p>{item && <><ItemStats item={item}/><button type="button" disabled={pendingAction === `unequip:${slot}`} onClick={() => onUnequip?.(slot)} className="mt-3 rounded-lg bg-slate-100 px-3 py-2 text-xs font-black text-slate-600 disabled:opacity-50">{pendingAction === `unequip:${slot}` ? '処理中…' : '解除'}</button></>}</div>; })}</div><div><h2 className="text-xl font-black text-slate-800">所持装備</h2><div className="mt-4 space-y-5">{EQUIPMENT_SLOTS.map((slot) => <div key={slot}><h3 className="text-sm font-black text-slate-600">{SLOT_LABELS[slot]}</h3>{grouped[slot].length === 0 ? <p className="mt-2 text-xs font-bold text-slate-400">まだ装備を持っていません</p> : <div className="mt-2 grid gap-3 sm:grid-cols-2">{grouped[slot].map((item) => { const equipped = isEquipmentEquipped(safe, item); return <div key={item.id} className="min-w-0 rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><p className="break-words font-black text-slate-800">{item.name}</p><p className="mt-1 text-xs font-bold text-slate-500">{item.description || '説明はありません。'}</p><ItemStats item={item}/>{equipped ? <p className="mt-3 text-xs font-black text-emerald-600">装備中</p> : <button type="button" disabled={pendingAction === `equip:${item.id}`} onClick={() => onEquip?.(item.id)} className="mt-3 rounded-lg bg-blue-600 px-3 py-2 text-xs font-black text-white disabled:bg-slate-300">{pendingAction === `equip:${item.id}` ? '処理中…' : '装備する'}</button>}</div>; })}</div>}</div>)}</div></div></section>;
}
