import { ALCHEMY_ITEMS, GACHA_RATES, MEMBER_RATES, TICKET_PRICES, TICKET_TYPES, getGachaResultName } from '../../rpg/gachaCatalog.js';

const names = { normal: 'NORMAL', silver: 'SILVER', gold: 'GOLD', premium: 'PREMIUM' };

export default function GachaPanel({ profile, onBuy, onDraw, onExchange, pending }) {
  const gacha = profile?.gacha || {};
  const balances = gacha.ticketBalances || {};
  const srRemaining = Math.max(0, 10 - (gacha.drawsSinceSrPlus || 0));
  const ssrRemaining = Math.max(0, 20 - (gacha.drawsSinceSsr || 0));
  const exchangeChoices = [['ticket', 'silver', 'SILVER 80'], ['ticket', 'gold', 'GOLD 150'], ['ticket', 'premium', 'PREMIUM 350'], ...Object.values(ALCHEMY_ITEMS).filter((item) => item.rarity === 'R' || item.rarity === 'SR').map((item) => ['item', item.id, `${item.name} ${item.rarity === 'R' ? 25 : 60}`])];
  return <section className="space-y-6"><div><p className="text-[10px] font-black tracking-widest text-violet-600">STUDY GACHA</p><h2 className="text-xl font-black text-slate-800">学習ガチャ</h2><p className="text-sm font-bold text-slate-500">{ssrRemaining === 0 ? '次回 SSR確定' : srRemaining === 0 ? '次回 SR以上確定' : `SR以上確定まで あと ${srRemaining}回 / SSR確定まで あと ${ssrRemaining}回`}</p></div><div className="grid gap-3 sm:grid-cols-2">{TICKET_TYPES.map((type) => <article key={type} className="rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><div className="flex justify-between"><b>{names[type]}</b><span>所持 {balances[type] || 0}</span></div><p className="mt-2 text-xs text-slate-500">{TICKET_PRICES[type]} GOLD</p><div className="mt-3 flex gap-2"><button type="button" disabled={pending} onClick={() => onBuy(type)} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-black">購入</button><button type="button" disabled={pending || !(balances[type] || 0)} onClick={() => onDraw(type)} className="rounded-lg bg-violet-600 px-3 py-2 text-xs font-black text-white disabled:bg-slate-300">1回引く</button></div></article>)}</div><div className="rounded-2xl bg-amber-50 p-4"><b>スターのかけら：{gacha.starFragments || 0}</b><div className="mt-3 flex flex-wrap gap-2">{exchangeChoices.map(([kind, id, label]) => <button type="button" key={id} disabled={pending} onClick={() => onExchange(kind, id)} className="rounded-lg bg-white px-3 py-2 text-xs font-bold shadow-sm disabled:opacity-50">{label}</button>)}</div></div><div className="rounded-2xl border border-slate-100 p-4 text-xs"><b>チケット別レアリティ排出率</b><div className="mt-2 grid gap-2 sm:grid-cols-2">{TICKET_TYPES.map((type) => <p key={type}><b>{names[type]}</b> N{GACHA_RATES[type].N}% / R{GACHA_RATES[type].R}% / SR{GACHA_RATES[type].SR}% / SSR{GACHA_RATES[type].SSR}%</p>)}</div><b className="mt-4 block">レアリティごとの Member / Item</b>{Object.entries(MEMBER_RATES).map(([rarity, memberRate]) => <p key={rarity} className="mt-1">{rarity}：Member {memberRate}% / Item {100 - memberRate}%</p>)}</div><div><h3 className="font-black">最近の結果</h3><div className="mt-2 space-y-2 text-sm">{(gacha.recentDraws || []).length ? gacha.recentDraws.map((draw, index) => <div key={`${draw.drawnAt}-${index}`} className="rounded-lg bg-slate-50 p-2"><b>{draw.rarity} {draw.resultType === 'member' ? 'MEMBER' : 'ITEM'}</b><p>{getGachaResultName(draw)}</p>{draw.duplicate && <p className="font-black text-amber-700">DUPLICATE スターのかけら +{draw.starFragmentsGained}</p>}</div>) : <p className="text-slate-400">まだありません</p>}</div></div></section>;
}
