import { useState } from 'react';
import { MATERIAL_DEFS, MATERIAL_KEYS } from '../../rpg/rewardConfig.js';
import { MATERIAL_EXCHANGE_GIVE, MATERIAL_EXCHANGE_RECEIVE } from '../../data/rpgMaterialExchangeRepository.js';

export default function MaterialExchange({ profile, onExchangeRequest, pending }) {
  const [sourceMaterialKey, setSourceMaterialKey] = useState('');
  const [targetMaterialKey, setTargetMaterialKey] = useState('');
  const sourceCount = Number(profile?.materials?.[sourceMaterialKey]) || 0;
  const canExchange = sourceMaterialKey && targetMaterialKey && sourceMaterialKey !== targetMaterialKey && sourceCount >= MATERIAL_EXCHANGE_GIVE;
  return <section className="space-y-5"><div><p className="text-[10px] font-black tracking-widest text-violet-600">MATERIAL EXCHANGE</p><h2 className="text-xl font-black text-slate-800">素材交換所</h2><p className="mt-1 text-xs font-bold text-slate-500">好きな素材を{MATERIAL_EXCHANGE_GIVE}個出すと、別の素材を{MATERIAL_EXCHANGE_RECEIVE}個もらえるよ。</p></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-black text-slate-600">出す素材<select value={sourceMaterialKey} onChange={(event) => setSourceMaterialKey(event.target.value)} disabled={pending} className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm"><option value="">選んでください</option>{MATERIAL_KEYS.map((key) => <option key={key} value={key}>{MATERIAL_DEFS[key].label}（{Number(profile?.materials?.[key]) || 0}個）</option>)}</select></label><label className="text-xs font-black text-slate-600">欲しい素材<select value={targetMaterialKey} onChange={(event) => setTargetMaterialKey(event.target.value)} disabled={pending} className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm"><option value="">選んでください</option>{MATERIAL_KEYS.map((key) => <option key={key} value={key} disabled={key === sourceMaterialKey}>{MATERIAL_DEFS[key].label}</option>)}</select></label></div>{sourceMaterialKey && sourceCount < MATERIAL_EXCHANGE_GIVE && <p className="text-xs font-bold text-rose-600">交換には{MATERIAL_DEFS[sourceMaterialKey].label}があと{MATERIAL_EXCHANGE_GIVE - sourceCount}個必要です。</p>}<button type="button" disabled={!canExchange || pending} onClick={() => onExchangeRequest?.({ sourceMaterialKey, targetMaterialKey })} className="w-full rounded-xl bg-violet-600 py-3 text-sm font-black text-white disabled:cursor-not-allowed disabled:bg-slate-300">{pending ? '交換処理中…' : `${MATERIAL_EXCHANGE_GIVE}個 → ${MATERIAL_EXCHANGE_RECEIVE}個を確認する`}</button></section>;
}
