import { useState } from 'react';
import { ELEMENT_LABELS } from '../../rpg/elementConfig.js';

export default function PartyBattleArena({ battle, onAttack, onSkill, attacking, feedback }) {
  const [enemyId, setEnemyId] = useState(battle.enemyStates.find((state) => state.status === 'active')?.enemyInstanceId || null); const [allyId, setAllyId] = useState(battle.activePartyMemberId);
  const actor = battle.partySnapshot.members.find((member) => member.memberId === battle.activePartyMemberId); const aliveEnemies = battle.enemyStates.filter((state) => state.status === 'active');
  const skillUses = (skill) => Number(battle.skillUses?.[`${actor.memberId}:${skill.id}`] || 0);
  return <section className="rounded-[2rem] bg-gradient-to-br from-slate-900 to-indigo-900 p-5 text-white"><p className="text-xs font-black text-indigo-200">ROUND {battle.roundNumber} ・ {actor?.name}のターン</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{battle.enemySnapshots.map((enemy) => { const state = battle.enemyStates.find((item) => item.enemyInstanceId === enemy.enemyInstanceId); const selected = enemyId === enemy.enemyInstanceId; return <button type="button" disabled={state.status !== 'active'} onClick={() => setEnemyId(enemy.enemyInstanceId)} key={enemy.enemyInstanceId} className={`rounded-xl p-3 text-left ${selected ? 'ring-2 ring-amber-300 bg-rose-700' : 'bg-white/10'} disabled:opacity-40`}><b>{enemy.name}</b><p className="text-xs">{ELEMENT_LABELS[enemy.element] || '無'} / HP {state.hp}/{enemy.maxHp}</p><p className="text-[10px]">弱点 {(enemy.weaknesses || []).join('・') || 'なし'} / 耐性 {(enemy.resistances || []).join('・') || 'なし'}</p>{selected && <p className="mt-1 text-xs font-black">TARGET</p>}</button>; })}</div><div className="mt-4 grid gap-2 sm:grid-cols-3">{battle.partySnapshot.members.map((member) => { const state = battle.partyStates.find((item) => item.memberId === member.memberId); return <button type="button" disabled={state.status !== 'active'} onClick={() => setAllyId(member.memberId)} key={member.memberId} className={`rounded-xl p-3 text-left ${allyId === member.memberId ? 'bg-emerald-600 ring-2 ring-emerald-200' : 'bg-white/10'} disabled:opacity-40`}><b>{member.name}</b><p className="text-xs">{member.role} / HP {state.hp}/{member.maxHp}</p><p className="text-[10px]">{state.status === 'defeated' ? '戦闘不能' : state.guardPercent ? `Guard ${state.guardPercent}%` : '行動可能'}</p></button>; })}</div><button type="button" disabled={attacking || !aliveEnemies.length} onClick={() => onAttack?.(enemyId)} className="mt-5 w-full rounded-xl bg-rose-500 py-3 font-black disabled:bg-slate-500">通常攻撃</button><div className="mt-4 space-y-2">{(actor?.skills || []).map((skill) => <button type="button" key={skill.id} disabled={attacking || skillUses(skill) >= skill.maxUses} onClick={() => onSkill?.(skill.id, skill.targetType === 'single_enemy' ? enemyId : null, skill.targetType === 'single_ally' ? allyId : null)} className="w-full rounded-xl bg-indigo-500 py-3 text-left px-4 font-black disabled:bg-slate-500">{skill.name} <span className="text-xs">{skill.targetType} / 残り {skill.maxUses - skillUses(skill)}</span></button>)}</div>{feedback?.length > 0 && <div className="mt-4 rounded-xl bg-white/10 p-3 text-sm">{feedback.map((line, index) => <p key={`${line}-${index}`}>{line}</p>)}</div>}</section>;
}
