import { MATERIAL_DEFS } from '../../rpg/rewardConfig.js';
import { normalizePlayerProfile } from '../../rpg/playerProfile.js';
import { getEquipmentDisplayStats } from '../../rpg/equipmentDisplay.js';

export default function PurchaseConfirmModal({ item, profile, onCancel, onConfirm, purchasing }) {
  if (!item) return null;
  const safe = normalizePlayerProfile(profile || {});
  const gold = Number(safe.gold) || 0;
  const stats = getEquipmentDisplayStats(item);
  return <div className="fixed inset-0 z-[160] flex items-center justify-center bg-slate-900/60 p-4"><section role="dialog" aria-modal="true" className="w-[calc(100vw-32px)] max-w-md rounded-[2rem] bg-white p-6 shadow-2xl"><h2 className="text-xl font-black text-slate-800">{item.name}を購入しますか？</h2><p className="mt-2 text-xs font-bold text-slate-500">購入後は装備画面から装備できます。</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs font-black"><div className="rounded-lg bg-blue-50 p-2 text-blue-700">攻撃力 +{stats.attack}</div><div className="rounded-lg bg-emerald-50 p-2 text-emerald-700">防御力 +{stats.defense}</div></div><p className="mt-2 text-xs font-bold text-slate-500">特殊能力：{stats.specialAbilityLabel}</p><div className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm"><div className="font-black text-slate-700">必要</div><div className="mt-2 font-black text-amber-700">{Number(item.cost?.gold || 0).toLocaleString('ja-JP')} GOLD</div>{Object.entries(item.cost?.materials || {}).map(([key, required]) => <div key={key} className="mt-1 text-xs font-bold text-slate-600">{MATERIAL_DEFS[key]?.label || key} ×{required}</div>)}</div><div className="mt-4 rounded-2xl border border-blue-100 p-4 text-xs font-bold text-slate-600"><div className="font-black text-slate-700">購入後</div><div className="mt-2">GOLD {gold.toLocaleString('ja-JP')} → {Math.max(0, gold - (Number(item.cost?.gold) || 0)).toLocaleString('ja-JP')}</div>{Object.entries(item.cost?.materials || {}).map(([key, required]) => { const current = Number(safe.materials?.[key]) || 0; return <div key={key} className="mt-1">{MATERIAL_DEFS[key]?.label || key} {current} → {Math.max(0, current - Number(required || 0))}</div>; })}</div><div className="mt-6 grid grid-cols-2 gap-3"><button type="button" disabled={purchasing} onClick={onCancel} className="rounded-xl bg-slate-100 py-3 text-sm font-black text-slate-600 disabled:opacity-50">キャンセル</button><button type="button" disabled={purchasing} onClick={onConfirm} className="rounded-xl bg-blue-600 py-3 text-sm font-black text-white disabled:bg-slate-300">{purchasing ? '購入処理中…' : '購入する'}</button></div></section></div>;
}
